### PR TITLE
Fix spelling mistakes

### PR DESCRIPTION
**Pull request by 1ace**

### CODE REVIEW

**Comment by RaoOfPhysics** [comment]
@1ace: Thanks so much for these. @tiborsimko: FWIW, I've double-checked the edits and they look good to me. Please merge when you can. :)

**Comment by tiborsimko** [comment]
@1ace Thanks for your contributions! Since this is your first commit to one of the cernopendata repositories, I have to ask you some legalese: 

- [ ] Can you please confirm by replying to this comment that you agree to donate this (and any further) contribution to the cernopendata repositories under the terms of the [GNU GPLv2](https://www.gnu.org/licenses/old-licenses/gpl-2.0) free software licence? 

- [ ] Are you OK to keep the copyright CERN statement in the touched files or would you like to add a line for your institution to the files you modified?

Thanks for your understanding :smile:

**Comment by 1ace** [comment]
@tiborsimko Yes to both: my contributions fall under the current license, and there's no need to modify the copyright :+1:

Can you even copyright spelling fixes? ^^
*As much as I find the idea amusing, I'm actually curious about the answer :)*

**Comment by RaoOfPhysics** [comment]
@1ace: I am not a lawyer, but I don't believe fixing spelling mistakes constitutes significant "creative expression" to merit copyright assignment. :)

**Comment by tiborsimko** [comment]
@RaoOfPhysics That's possible, however a contribution is a contribution, and @1ace also suggested UI code changes in the other pull request (#937),  so it's usually easier to get the legal stuff right before the very first contribution, and we are good for any possible future PRs.

@1ace I'll squash your PR as we usually avoid explicit merge commits in order to keep the commit history clean.

(BTW see also the [GNU project practices](https://www.gnu.org/prep/maintain/html_node/Copyright-Papers.html), e.g. many years ago I had to scan my ID and mail it to FSF HQ as part of the procedures... that's to be on the really safe side :smile: )

**Comment by tiborsimko** [comment]
Thanks, merged as:

- 7a28daafb0871169489a27067103b9b3470dac27 CMS: fix spelling mistakes
- d41d4bf6ea955b326b72dfa6764a1c6c513c1797 base: fix spelling mistakes

**Pull request closed without merging**
