### PR TITLE
CMS - HIRun2011 datasets

### LINKED ISSUE #2913: CMS - build data records for 2011 PbPb
Build four data records for 2011 PbPb cms-primary-datasets-HIRun2011.json

(see https://github.com/cernopendata/data-curation/issues/78)

### 2011 PbPb slc5, CMSSW_3_9_X/CMSSW_4_4:
- /HIDiMuon/HIRun2011-04Mar2013-v1/RECO [reco config](https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/9bdeb0f079eab5b1f4a738ac03779f93/configFile)				
- /HIHighPt/HIRun2011-15Apr2013-v1/RECO [reco config](https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/9bdeb0f079eab5b1f4a738ac03779f93/configFile)
- /HIMinBiasUPC/HIRun2011-12Jun2013-v1/RECO [reco config](https://cmsweb.cern.ch/couchdb/reqmgr_config_cache/d7f380b9595d89f1816e6b06929e2f3d/configFile)			
- /MinimumBias/HIRun2011-PromptReco-v1/RECO	no reco config			

Reco config records see #2914

### PR DESCRIPTION
**Pull request by katilp**
(closes #2913 )

Add 4 2011 PbPb records + 1 interfill record

To fix: recids for the config files (see #2914), now 0000

### CODE REVIEW

**Comment by katilp** [comment]
One more record coming /ForwardTriggers/HIRun2011-PromptReco-v1/RECO (interfill 0 TeV)

**Comment by tiborsimko** [comment]
> **Done:** One more record coming /ForwardTriggers/HIRun2011-PromptReco-v1/RECO (interfill 0 TeV)

I'll transfer the last dataset to its final destination (from `/eos/opendata/cms/upload/hidata/HIRun2011/ForwardTriggers/RECO/PromptReco-v1`).

**Comment by tiborsimko** [comment]
> I'll transfer the last dataset to its final destination (from `/eos/opendata/cms/upload/hidata/HIRun2011/ForwardTriggers/RECO/PromptReco-v1`).

All files ready, creating indexes for:

```
    "title": "/HIDiMuon/HIRun2011-04Mar2013-v1/RECO",
    "title": "/HIHighPt/HIRun2011-15Apr2013-v1/RECO",
    "title": "/HIMinBiasUPC/HIRun2011-12Jun2013-v1/RECO",
    "title": "/MinimumBias/HIRun2011-PromptReco-v1/RECO",
    "title": "/ForwardTriggers/HIRun2011-PromptReco-v1/RECO",
```

**Comment by tiborsimko** [comment]
> To fix: recids for the config files (see #2914), now 0000

Leaving 0000 in the PR, we can update them after config file records are created. I'll leave a note about this in the issue.

**Review by tiborsimko — APPROVED** [review]
Added file information and merging...

**Pull request merged**
