### PR TITLE
templates: Fix IPPOG link to new website

### PR DESCRIPTION
**Pull request by RaoOfPhysics**
Signed-off-by: Achintya Rao <achintya.rao@cern.ch>

### CODE REVIEW

**Comment by RaoOfPhysics** [comment]
Quick fix!

**Comment by ioannistsanaktsidis** [comment]
@RaoOfPhysics  please rebase against latest master and I will merge it :)

**Comment by RaoOfPhysics** [comment]
@ioannistsanaktsidis: Rebase didn't seem to work properly, but this should be OK I guess. Let me know if anything needs to be changed!

**Comment by ioannistsanaktsidis** [comment]
Merging

**Pull request merged**
