### PR TITLE
Add Run1 RAW

### PR DESCRIPTION
**Pull request by katilp**
Adds Run1 RAW - addresses #2439 
  - needs recid's and DOIs for (4 new record 2010, 5 new records 2011, 6 new records 2012)
  - needs config files added, (edit:) get them from the list in the comment below
  - needs n of files and size

Adds also the methodology and a link to trigger configuration for 2010 RAW (in the same way as now in 2010 AOD)

### CODE REVIEW

**Comment by katilp** [comment]
Config files for each dataset are to be copied from (not linked to as this will move) :
- 2010 Electron: https://raw.githubusercontent.com/cms-legacydata-validation/RAWToAODValidation/2010/code/Electron/configDump_raw_Electron10.py
- 2010 Jet: https://raw.githubusercontent.com/cms-legacydata-validation/RAWToAODValidation/2010/code/Jet/configDump_raw_Jet10.py
- 2010 MinimumBias: https://raw.githubusercontent.com/cms-legacydata-validation/RAWToAODValidation/2010/code/Mu/configDump_raw_Mu10.py

(2010 config files are fully expanded because parts for estimating the luminosity - not needed in re-reco phase and not functinal in the open data environment - had to be removed in various positions in the file)

- 2011 DoubleElectron: https://raw.githubusercontent.com/cms-legacydata-validation/RAWToAODValidation/2011/code/DoubleElectron/raw_DoubleElectron11.py
- 2011 DoubleMu: https://raw.githubusercontent.com/cms-legacydata-validation/RAWToAODValidation/2011/code/DoubleMu/raw_DoubleMu11.py
- 2011 Jet: https://raw.githubusercontent.com/cms-legacydata-validation/RAWToAODValidation/2011/code/Jet/raw_Jet11.py
- 2011 SingleElectron: https://raw.githubusercontent.com/cms-legacydata-validation/RAWToAODValidation/2011/code/SingleElectron/raw_SingleElectron11.py
- 2011 SingleMu: https://raw.githubusercontent.com/cms-legacydata-validation/RAWToAODValidation/2011/code/SingleMu/raw_SingleMu11.py

for 2012 datasets, extensive rereco testing has not been done, only a quick verification, and we may want to indicate this with a generic config (without the input file name whereas the configs above have the example root file in the input file path that actually has been tested and compared to the original AOD)

**Comment by katilp** [comment]
@tiborsimko If the config file above are attached to the record, what would be the appropriate json field to describe them? Probably `usage`?

**Comment by tiborsimko** [comment]
In the "usage" field we only have "description" and "links" properties, so we'd need to add a new one to store config snippets, like we did for "script" in the "methodology" part... Alternatively, if some of them can become big, we can store them all as files on EOS, as for the collision data configs.

**Comment by katilp** [comment]
2010 configs are very big as they are fully expanded, it would not be practical to show then like we do for "script"

**Comment by katilp** [comment]
All the config files mentioned above are now uploaded in
`/eos/opendata/cms/upload/kati/RAWtoAODconfigs`

**Pull request merged**
