### PR TITLE
CMS: new 2011 RAW dataset sample and rereco software records

### LINKED ISSUE #1202: CMS: add a raw data sample
CMS CB approved releasing (order of) 1M events in RAW format from Minimum bias dataset

- [x] Choose a set of files (a block in DAS?) to release
   - parent data for http://opendata.cern.ch/record/24
   - size of 1M events
   - has enough events passing validation (not mandatory for known use-cases of these data but maybe useful for others)
- [x] Check whether the sample could be reconstructed with http://opendata.cern.ch/record/3610/files/configFile.py and using the currently available global tag FT_53_LV5_AN1
- [ ] Add instructions and limitations
- [ ] Add a new collection for "CMS raw data"

### LINKED ISSUE #1525: CMS: create new software records for RAW dataset
Generate two new software records, as per the discussion in #1202:

1. a new record based on https://github.com/cms-opendata-validation/recotest 

2. a new record based on https://github.com/katilp/compare-rereco

### PR DESCRIPTION
**Pull request by tiborsimko**
* Introduces new record for 2011 RAW data sample. (closes #1202)

* Introduces two new software records for the RAW data sample. (closes #1525)

* Note: PR prepared from COD2 PR #1546.

* Also fixes distribution.formats for other `tar.gz` files.

Co-authored-by: Tibor Simko <tibor.simko@cern.ch>
Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

### CODE REVIEW

**Comment by tiborsimko** [comment]
@ArtemisLav @katilp Everything is ready for COD3, files included. The only missing information is the total number of events in the 2011 MinimumBias RAW sample. It's about 1M, but we should calculate how much exactly...

**Comment by katilp** [comment]
OK, thanks, I'll have a look on CMSDAS for n_events

**Comment by katilp** [comment]
The number of events is 1913190 (see 
https://github.com/cernopendata/opendata.cern.ch/issues/1202#issuecomment-338120511)

**Comment by tiborsimko** [comment]
@katilp Thanks, PR updated. If you check the information and approve the PR, I can merge and deploy.

**Pull request merged**
