### PR TITLE
CMS:link the author list to 2011 configuration files

### PR DESCRIPTION
**Pull request by AnxhelaDani**
Addition of `110__$w` according to https://github.com/cernopendata/opendata.cern.ch/issues/954#issuecomment-207347572

### CODE REVIEW

**Comment by tiborsimko** [comment]
@AnxhelaDani Is this still a work in progress?

**Comment by AnxhelaDani** [comment]
Yes @tiborsimko, tomorrow will be done.

**Comment by AnxhelaDani** [comment]
@tiborsimko additions done, ready for merge. Thanks!

**Comment by tiborsimko** [comment]
Thanks, squashed and merged as 39d9e7b56e39ecb91d172153a1a9e019d35e4e2b.

**Pull request closed without merging**
