### PR TITLE
Create cms-mc-template

### PR DESCRIPTION
**Pull request by pherterich**
first attempt on a template for #820 by @AnxhelaDani and me. @tiborsimko let us know if things are unclear. Some fields will need to be added to the data model. Sorry for the new patch again, was already created when I remembered I should have done this in my own fork... Can be deleted once you upload the real files.

### CODE REVIEW

**Comment by tiborsimko** [comment]
Thanks, this is helpful. I'll look at DAS to see what we can complete...

**Comment by tiborsimko** [comment]
The generated CMS Simulated Dataset records can be seen on the DEV box:

- http://opendatadev.cern.ch/search?cc=CMS-Simulated-Datasets

**Comment by AnxhelaDani** [comment]
The text for 581 field is 
$a You can access these data through the CMS Virtual Machine. See the instructions for setting up the Virtual Machine and getting started in
$u http://opendata.cern.ch/VM/CMS
$y How to install the CMS Virtual Machine
581
$u http://opendata.cern.ch/getting-started/CMS
$y Getting started with CMS open data

**Comment by tiborsimko** [comment]
@AnxhelaDani Thanks, added to the template.

**Pull request closed without merging**
