### PR TITLE
Update cms-tools-vm-image.xml

### PR DESCRIPTION
**Pull request by pherterich**
Needs files attached as FFT

### CODE REVIEW

**Comment by tiborsimko** [comment]
> Needs files attached as FFT

@pherterich From where do I get contextualisation script files to be attached as FFT?

**Comment by pherterich** [comment]
They should be in your inbox. E-mail from 3rd of march titled "CODP - record 249 - Files"

**Comment by tiborsimko** [comment]
@pherterich Got it, thanks. :smile:

**Comment by tiborsimko** [comment]
Thanks, amended commit log, added FFT tags and files, and merged.

**Comment by tiborsimko** [comment]
@pherterich @katilp Some comments to the record.  I've added all the files literally, i.e. we have three attached files:

   - `cernvm-script`
   - `cms-user-data.txt`
   - `opendata-desktop-settings`

but I think we may want to:  (1) consider renaming some files perhaps (so that scripts end with `.sh`); 
(2) check the contents (e.g. `cernvm-script` uses `https://github.com/cernvm/cernvm-config/blob/master/usr/bin/cvm2ova` which is a moving target due to `master` branch; could we take some tagged released version?); (3) check whether a file is needed (`opendata-desktop-settings` with only `[Desktop Entry]` which is kind of user dependent thing not needed for preservation?).

**Pull request closed without merging**
