### PR TITLE
CMS:addition of run period in masterclass-files.xml

### PR DESCRIPTION
**Pull request by AnxhelaDani**
Addition of `964_0$c`

### CODE REVIEW

**Comment by tiborsimko** [comment]
@AnxhelaDani Is this still work-in-progress?

**Comment by AnxhelaDani** [comment]
Yes @tiborsimko. Today it will be done.

**Comment by AnxhelaDani** [comment]
@tiborsimko ready for merge, thanks!

**Comment by tiborsimko** [comment]
Thanks, squashed and merged as 6285e2e9b54d42d3e5162a928728dd68cf3993a7.

**Pull request closed without merging**
