### PR TITLE
Edited cms_learning_resources to add the new link and screenshot for …

### PR DESCRIPTION
**Pull request by mattbellis**
…the Particle Physics Playground.

### CODE REVIEW

**Comment by tiborsimko** [comment]
Thanks, I've amended the screenshot file name back to the original one and merged as f7f819823926c3b4a40ca42838a86120219416d6.

**Comment by mattbellis** [comment]
Was the CERN Open Data site rebuilt with this pull added? I don't see the new screenshot and the link is still the old one. 

http://opendata.cern.ch/collection/CMS-Learning-Resources

**Comment by RaoOfPhysics** [comment]
@mattbellis: You'll need to SSH in to CERN and go to: http://opendatadev.cern.ch/collection/CMS-Learning-Resources

**Comment by mattbellis** [comment]
@RaoOfPhysics I don't understand. Is the new screenshot only visible on an only-internally-visible development branch? When are new changes deployed publicly?

**Comment by mattbellis** [comment]
@RaoOfPhysics FWIW, the edit looks pretty good when I view that developer version! :)

**Comment by RaoOfPhysics** [comment]
@mattbellis: @tiborsimko can comment on the development procedures, but yes, for now, the changes are only available on the internal-only branch.

**Comment by mattbellis** [comment]
OK, sounds good. I'm only wondering because I've submitted a grant that will probably be reviewed this winter/early-spring and a good portion of it was this outreach effort and how it ties in with the Open Data portal. I'd hate for someone to be browsing the official site and come across the old version and wonder what I was referring to in the grant. @tiborsimko do you know when these changes might be deployed for the publicly visible version?

**Comment by tiborsimko** [comment]
@mattbellis The change was deployed on the production this morning. Sorry for the delay!

**Pull request closed without merging**
