### PR TITLE
templates: CMS: replace cms links

### PR DESCRIPTION
**Pull request by atrisovic**
* Closes: #1586

Signed-off-by: Ana Trisovic <ana.trisovic@gmail.com>

### CODE REVIEW

**Comment by RaoOfPhysics** [comment]
Will review.

**Comment by ioannistsanaktsidis** [comment]
@atrisovic is this one ready ?

**Comment by atrisovic** [comment]
yes, this one is ready too. for the physics object there is another issue (#1592).

**Comment by ioannistsanaktsidis** [comment]
Ok I will merge first #1875  and then you can rebase this one and merge it.

**Comment by ioannistsanaktsidis** [comment]
@katilp or @RaoOfPhysics  please approve so as to merge this one.

**Comment by katilp** [comment]
I think I approve 😄

**Pull request merged**
