### PR TITLE
sitemap: add sitemap package

### LINKED ISSUE #2274: sitemap: add sitemap
Introduce sitemap to ease record discovery.  (Stemmed from #1324.)  

See also:

- `Flask-Sitemap`
- `zenodo/modules/sitemap`

Since we don't have much dynamic uploads, rather planned releases, we could even pre-generate the sitemap files during image build time, without having to have the worker node do this "live" regularly.

### PR DESCRIPTION
**Pull request by diegodelemos**
* (closes #2274).

### CODE REVIEW

**Comment by diegodelemos** [comment]
To test:
```console
$ ./scripts/populate-instance.sh
$ mkdir cernopendata/modules/sitemap/static
$ cernopendata sitemap generate -o cernopendata/modules/sitemap/static
...
Writing sitemap 0 file: cernopendata/modules/sitemap/static/sitemap0.xml ...
Writing sitemap index file: cernopendata/modules/sitemap/static/sitemap.xml ...
```

**Comment by jirikuncar** [comment]
Hi @diegodelemos, just out of curiosity, is there any problem with [Flask-Sitemap](https://github.com/inveniosoftware/flask-sitemap)?

**Comment by tiborsimko** [comment]
@diegodelemos Yes, let's remove the CLI.  The number of records on COD3 remains relatively small (~4,000), so that the sitemap generation remains quick.  (I guess we won't need to include direct links to files there one day, because that would be ~400,000!)

@jirikuncar The guys tried on Zenodo some time ago, but get into some issues (IIRC doing sitemap in memory etc) so they went for "bibsched task" like solution with a nightly celery task generating the sitemaps. Otherwise I fully agree that we should revive the `Flask-Sitemap` package or make a general `invenio-sitemaps` one...

**Comment by ioannistsanaktsidis** [comment]
@diegodelemos please rebase so as to check and merge it directly :).

**Comment by tiborsimko** [comment]
@ioannistsanaktsidis I wouldn't approve it if it did not work for me locally 😄 Taking care of merging...

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko yes I was going to test it, but I saw that you approved already before I comment. Anyway will test it locally either way :)

**Pull request merged**
