### PR TITLE
Update VMs to 1.5.3 and 1.1.4

### LINKED ISSUE #2847: CMS: new VM to replace the failing one
[cernvm-script.txt](https://github.com/cernopendata/opendata.cern.ch/files/4823748/cernvm-script.txt)
A new VM http://cernvm.cern.ch/releases/CMS-OpenData-1.5.2.ova
needs to be added to http://opendata.cern.ch/record/252 to replace 1.5.1.

Add the contextualization script record, the vm uses
- [cernvm-script.txt](https://github.com/cernopendata/opendata.cern.ch/files/4823748/cernvm-script.txt)
- the images from http://cernvm.cern.ch/releases/production/cernvm4-micro-2020.04-1.hdd

Update the instructions in http://opendata.cern.ch/docs/cms-virtual-machine-2011
- [x] 1.5.1 -> 1.5.2
- [x] update the latest tested VirtualBox to 6.0.22 
- [x] add instructions how to open the image in VirtualBox (see also https://github.com/cernopendata/opendata.cern.ch/issues/2602#issuecomment-513564792) (de-select "import disks as VDI" on initial import screen)

@jblomer Are the old VMs 1.2.0 and 1.3.0 affected as well? If needed, we can mark them deprecated.

### PR DESCRIPTION
**Pull request by katilp**
(closes #2847) 

To do at merge:
- vm file for record 252 from  https://cernvm.cern.ch/releases/CMS-OpenData-1.5.3.ova
- the 3 context files for the **new record 257** from root://eospublic.cern.ch//eos/opendata/cms/environment/1.5.2/

- vm file for record 250 from https://cernvm.cern.ch/releases/CMS-OpenData-1.1.4.ova
- the context file cms-user-data.txt for the **new record 248** from https://raw.githubusercontent.com/cernvm/public-contexts/master/cms-opendata.context , the two others scripts the same as 1.5.2 (see above)

### CODE REVIEW

**Comment by tiborsimko** [comment]
>  the two others scripts the same as 1.5.2 (see above)

@jblomer [has mentioned](https://github.com/cernopendata/opendata.cern.ch/issues/2847#issuecomment-652863110) that 1.5.3 uses new base image, so I think we should update `cernvm-script` in the new 1.5.3-related contextualisation script record?

The 1.5.2 value was:

```
cvm2ova -n "CMS-OpenData-1.5.2" -d 40000 -m 2048 \
-i cernvm4-micro-2020.04-1.hdd \
-u cms-user-data.txt

https://github.com/cernvm/cernvm-config/blob/master/usr/bin/cvm2ova
```

The 1.5.3 value should probably say `2020.07` in its stead...

**Comment by katilp** [comment]
For 1.5.3, Jakob built it on the top of the April image (confirmed in the mail thread) so 2020.04 is OK.

**Comment by katilp** [comment]
Another point, do we need to display the deprecated images? They do not boot.

**Comment by tiborsimko** [comment]
Files copied (and amended `cernvm-script` to put resulting version number):

```
$ eos find --xurl --size --checksum /eos/opendata/cms/environment/1.1.4/
path=root://eospublic.cern.ch//eos/opendata/cms/environment/1.1.4/CMS-OpenData-1.1.4.ova size=20500480 checksum=cf2da029
path=root://eospublic.cern.ch//eos/opendata/cms/environment/1.1.4/cernvm-script size=181 checksum=9ed83782
path=root://eospublic.cern.ch//eos/opendata/cms/environment/1.1.4/cms-user-data.txt size=4968 checksum=50e7147c
path=root://eospublic.cern.ch//eos/opendata/cms/environment/1.1.4/opendata-desktop-settings size=152 checksum=786f33c7

$ eos find --xurl --size --checksum /eos/opendata/cms/environment/1.5.3
path=root://eospublic.cern.ch//eos/opendata/cms/environment/1.5.3/CMS-OpenData-1.5.3.ova size=20500480 checksum=974b2476
path=root://eospublic.cern.ch//eos/opendata/cms/environment/1.5.3/cernvm-script size=181 checksum=a0a83785
path=root://eospublic.cern.ch//eos/opendata/cms/environment/1.5.3/cms-user-data.txt size=4252 checksum=084361f5
path=root://eospublic.cern.ch//eos/opendata/cms/environment/1.5.3/opendata-desktop-settings size=152 checksum=786f33c7
```

I'll update the PR in this sense...

**Pull request merged**
