### PR TITLE
docker: add elasticsearch 5 support

### LINKED ISSUE #2001: docker: add elasticsearch 5 support
Currently Elasticsearch version used in Docker / Docker-Compose based installation is Elasticsearch 5.

-  [ ] Make changes to Docker / Docker-Compose files to enable use of Elasticsearch 5.

Note that _mapper-attachments_ -plugin has been deprecated (but still installable) in Elasticsearch 5 and replaced by  _ingest-attachment_ -plugin. (https://www.elastic.co/guide/en/elasticsearch/plugins/2.4/mapper-attachments.html)
However, since opendata.cern.ch is not using full text search / indexing this probably doesn't matter.

### PR DESCRIPTION
**Pull request by hjhsalo**
* Add necessary build argument (ES_VERSION) to specify which
  major version of Elasticsearch should be used.
  Tested with ES_VERSION=2 and ES_VERSION=5
  (closes #2001)

Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>

### CODE REVIEW

**Comment by hjhsalo** [comment]
Failing on Travis. Seems to fail on Dockerfile syntax, which works fine on my machine with Docker 17.09.0-ce. Probably Travis uses an older version of Docker.

**Comment by diegodelemos** [comment]
What about setting an environment variable (see [here](https://docs.docker.com/compose/compose-file/#variable-substitution)) in the shell that runs the `docker-compose` and then in the `docker-compose.yaml`:
```yaml
elasticsearch:
  restart: "always"
  build:
    context: .
    image: "elasticsearch:${ES_VERSION}"
    dockerfile: ./elasticsearch/Dockerfile
```
If this doesn't work, we could also try with two Dockerfiles, let say `./elasticsearch/Dockerfile.2` and `./elasticsearch/Dockerfile.5` each one with the corresponding `FROM` clause. Then inside the `docker-compose.yml` doing something like:
```yaml
elasticsearch:
  restart: "always"
  build:
    context: .
    dockerfile: ./elasticsearch/Dockerfile.${ES_VERSION}
```

**Comment by hjhsalo** [comment]
@diegodelemos 
In the end I updated Docker-CE and Docker-Compose on Travis-CI.

It adds a little bit of build time, but it seems to be kind of promoted by Travis-CI team as they have update instructions for Docker and Docker-compose in their "Using Docker in Builds" -document:
https://docs.travis-ci.com/user/docker/#Using-Docker-Compose
https://docs.travis-ci.com/user/docker/#Installing-a-newer-Docker-version

**Comment by diegodelemos** [comment]
could we get advantage of Travis caching using `apt-get` for `docker` install and `pip` for `docker-compose`? it is also listed among the best practices for `docker` installation

**Comment by diegodelemos** [comment]
taken over by #2080

**Pull request closed without merging**
