### PR TITLE
glossary: updates glossary UI

### LINKED ISSUE #1378: templates: /glossary
Improve styling of `/glossary` in `master` branch.

Mock-up at https://invenio.mybalsamiq.com/projects/cernopendatatopbarnavigation/Glossary

Display prominent "Glossary" title to show where we are.

Display navigation trail.

What about the output message "Found 22 results"? Could be misleading... Hide it? Or just position it more nicely?

### PR DESCRIPTION
**Pull request by ioannistsanaktsidis**
* Closes #1378.

Signed-off-by: Ioannis Tsanaktsidis <ioannis.tsanaktsidis@cern.ch>

### CODE REVIEW

**Comment by tiborsimko** [comment]
Is this still in the WIP state?  We could use labels such as `"Need: work"`, `"Need: tests`" instead of amending the title...

**Comment by ioannistsanaktsidis** [comment]
Updated with latest changes, after CI we can merge it.

**Comment by annatrz** [comment]
add breadcrumbs and we can merge

**Comment by ioannistsanaktsidis** [comment]
added

**Pull request merged**
