### PR TITLE
slugs: added slug key

### PR DESCRIPTION
**Pull request by atrisovic**
Signed-off-by: Ana Trisovic <ana.trisovic@gmail.com>

### CODE REVIEW

**Comment by tiborsimko** [comment]
@katilp Note that this PR standardises the URLs to the scheme proposed in #1753.  It also changes URLs in the page content e.g. `/docs/cms-guide-to-research-use-of-cms-open-data` is now `/docs/cms-guide-for-research`.  OK to push change this now, or shall we rather address it after the demo? (could be troublesome if you need to update links, but it would also not be good to advertise old links either...)

**Comment by katilp** [comment]
If  the old links i.e http://opendata-dev.web.cern.ch/docs/cms-guide-to-education-use-of-cms-open-data
won't work, I would very much like to delay this for tomorrow evening (we have a smaller DPOA meeting to get feedback tomorrow afternoon). But if redirecting is guaranteed, then fine.

**Comment by katilp** [comment]
But let me asap as I need to upload my slides soon 😃

**Comment by katilp** [comment]
I guess on the portal they do not appear in many locations (there is some cross-linking between guides and then links in about cms), I'll just update in my slides

**Comment by atrisovic** [comment]
no, don't worry, we'll merge this later :)

**Comment by katilp** [comment]
OK, perfect. I'll add a mention in my slides that they will be updated to
 http://opendata-dev.web.cern.ch/docs/cms-guide-for-research and http://opendata-dev.web.cern.ch/docs/cms-guide-for-education for future-proofness 😉

**Comment by katilp** [comment]
Updated  http://opendata-dev.web.cern.ch/docs/guide-to-the-cms-trigger-system
to /docs/cms-guide-trigger-system in my slides as well

**Comment by atrisovic** [comment]
I think this one is now ready to go

**Pull request merged**
