### PR TITLE
CMS event display fixes

### PR DESCRIPTION
**Pull request by tpmccauley**
These changes along with new version of ispy-webgl from bundles fixes issues in #1885

### CODE REVIEW

**Comment by ioannistsanaktsidis** [comment]
@tpmccauley  could you pls rebase against latest master and also squash the commits to 1 or 2 ?

**Comment by tpmccauley** [comment]
Ah. dammit. @ioannistsanaktsidis,  I did something worse!

My rebase and squash I thought looked fine, but yikes! How do I backup?

**Comment by ioannistsanaktsidis** [comment]
@tpmccauley you can do  on your branch ```git rebase -i <HEAD~NUMBER_OF_COMMITS_YOU_WANT_TO_EDIT> ``` e.g git rebase -i HEAD~30 and from that point you can mark the commits you want to delete. Let me know if you have any other problems.

**Comment by tpmccauley** [comment]
I keep getting something like this but don't see any conflicts:

Could not apply 5c35120e142329c718f83b497754fd6f274ed3f0... * increment version of ispy-webgl to fetch glyphicon fix

**Comment by ioannistsanaktsidis** [comment]
good thats because there are some conflicts now. You have to resolve the conflicts, then do ```git add <resolved-file>``` and then ```git rebase --continue```.

**Comment by tpmccauley** [comment]
So far so good. I have resolved the conflict and rebase is fine. However:
```
git push origin cms-evd
To https://github.com/tpmccauley/open-data.cern.ch.git
 ! [rejected]        cms-evd -> cms-evd (non-fast-forward)
error: failed to push some refs to 'https://github.com/tpmccauley/open-data.cern.ch.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
```

which is what got me in trouble in the first place I believe

**Comment by ioannistsanaktsidis** [comment]
@tpmccauley yes you need to force push. ```git push -f origin cms-evd``` ;)

**Comment by tpmccauley** [comment]
Done. Thanks!

**Comment by ioannistsanaktsidis** [comment]
There is one last conflict with bundles.py. Could you plse resolve it and push again ? thanks!

**Comment by ioannistsanaktsidis** [comment]
Closing as superseded by #2170 . Thanks @tpmccauley .

**Pull request closed without merging**
