### PR TITLE
elasticsearch: fix reindexing of records

### PR DESCRIPTION
**Pull request by hjhsalo**
* Fix reindexing of records (`cernopendata index reindex ...`)

Signed-off-by: Harri Hirvonsalo <harri.hirvonsalo@cern.ch>
Co-authored-by: Alexander Ioannidis <a.ioannidis@cern.ch>

### CODE REVIEW

**Comment by hjhsalo** [comment]
Just couple of notes how successful reindexing was determined:

After:
- bringing up development deployment (`docker-compose -f docker-compose-dev.yml up --build`)
- after populating the instance (`docker-compose -f docker-compose-dev.yml exec web ./scripts/populate-instance.sh --skip-files`):

Number of records and created indices:

```console
$ curl 'http://localhost:9200/_cat/indices?v'
health status index                        uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   records-software-v1.0.0      sVQeFYHoSN2hwjUorWbx1w   5   1          0            0       810b           810b
yellow open   records-docs-v1.0.0          9XBKncyRRTalJMUzNHNIXg   5   1         32            0    484.9kb        484.9kb
yellow open   records-data-policies-v1.0.0 AJMp1mEjSMi_hozXRGmqdA   5   1          0            0       810b           810b
yellow open   records-glossary-term-v1.0.0 UHX3vOGmQnidWcoo7GY-Jw   5   1         22            0    142.1kb        142.1kb
yellow open   records-datasets-v1.0.0      V0gUpJoHQdqrY1dRB6VwJg   5   1          0            0       810b           810b
yellow open   records-record-v1.0.0        CTgyAZuUQfeqzl1BKv82dw   5   1       3121            0      9.5mb          9.5mb
```

Number of hits returned by empty / all query (`http://127.0.0.1/api/records/?page=1&size=20&q=`)
```console
$ curl -s 'http://127.0.0.1:5000/api/records/?page=1&size=20&q=' | grep -e "\"total\":"
    "total": 3175
```

After:
- destroying Elasticsearch indices by stopping elasticsearch-container deleting volume attached to it container (`docker-compose -f docker-compose-dev.yml stop elasticsearch && docker rm -v opendatacernch_elastisearch_1`)
- recreating elasticsearch-container and creating an empty volume for it (`docker-compose -f docker-compose-dev.yml create elasticsearch && docker-compose -f docker-compose-dev.yml start elasticsearch`)
- recreating indices (`docker-compose -f docker-compose-dev.yml exec web cernopendata index init`)
- creating a reindexing queue (`docker-compose -f docker-compose-dev.yml exec web cernopendata index queue init`)
- populating reindexing queue with records, documents and glossary-terms (`docker-compose -f docker-compose-dev.yml exec web cernopendata index reindex -t recid -t docid -t termid --yes-i-know`)
- and executing the reindex queue (`docker-compose -f docker-compose-dev.yml exec web cernopendata index run --concurrency 1`)

```console
$ curl 'http://localhost:9200/_cat/indices?v'
health status index                        uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   records-software-v1.0.0      QjYZcmtsRfemfjYcwip1dQ   5   1          0            0       810b           810b
yellow open   records-docs-v1.0.0          FC1TqeZTS4OU--DZMLq-kw   5   1         32            0    461.3kb        461.3kb
yellow open   records-record-v1.0.0        pD2CLrNHSymPQXESVn5-nA   5   1       3121            0     10.6mb         10.6mb
yellow open   records-glossary-term-v1.0.0 _nNjPAOiT2WW_QQ4GRiKpw   5   1         22            0     98.2kb         98.2kb
yellow open   records-datasets-v1.0.0      si0PDkHiRTO-KdAmt6cF1Q   5   1          0            0       810b           810b
yellow open   records-data-policies-v1.0.0 uVh0K3lZSF2ml5oj2Ndnlw   5   1          0            0       810b           810b
```

Number of hits returned by empty / all query (`http://127.0.0.1/api/records/?page=1&size=20&q=`)
```console
$ curl -s 'http://127.0.0.1:5000/api/records/?page=1&size=20&q=' | grep -e "\"total\":"
    "total": 3175
```

**Comment by ioannistsanaktsidis** [comment]
@tiborsimko works good for me.  You can also take a look to be sure 100% that it is ok and we can merge it ;)

**Comment by tiborsimko** [comment]
Looks good, but after the merge of `elasticsearch-proxy`, I get:

```
 File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/invenio_indexer/cli.py", line 64, in run
    RecordIndexer(version_type=version_type).process_bulk_queue()
  File "/usr/lib/python2.7/site-packages/invenio_indexer/api.py", line 198, in process_bulk_queue
    request_timeout=req_timeout,
  File "/usr/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 190, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/usr/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 91, in _process_bulk_chunk
    raise e
elasticsearch.exceptions.TransportError: TransportError(413, u'<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body bgcolor="white">\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx/1.13.5</center>\r\n</body>\r\n</html>\r\n')
```

in production-like conditions... Need to enlarge some buffers? `http.max_content_length`?

**Comment by tiborsimko** [comment]
``
2017/12/14 15:01:13 [error] 7#7: *3227 client intended to send too large body: 1502144 bytes, client: 172.19.0.7, server: , request: "POST /_bulk HTTP/1.1", host: "elasticsearch-proxy"
```

**Pull request merged**
