### PR TITLE
Replace kbd with code in SimDataset Names (PR #1096)

### PR DESCRIPTION
**Pull request by RaoOfPhysics**

### CODE REVIEW

**Comment by katilp** [comment]
Note a missing / in 
         <li><code>PtW-300<code> if there is a lower cut on the W pthat</li>

**Comment by RaoOfPhysics** [comment]
@katilp: Thanks for the catch! Looks like it was a problem in the original edit too. :(

**Comment by RaoOfPhysics** [comment]
@tiborsimko: Perhaps you can check if this looks ok and let me know if I need to make any further changes before merging. Thanks!

**Comment by tiborsimko** [comment]
@RaoOfPhysics Yes, I'm always checking locally before merging :smile: The page was generally fine, so I preferred to merge and deploy yesterday, so that the content could be nailed down, treating the kbd/code suggestion as a simple further improvement...

**Comment by tiborsimko** [comment]
Thanks, merged as 239cecbfc62978f61a0941aa1cf7ce68b65ef781.

**Pull request closed without merging**
