### PR TITLE
LHCb Open Data Release Vol2

### PR DESCRIPTION
**Pull request by MindaugasSarpis**
Added 6 more stripping streams across all stripping versions. Added documentation pages for all stripping version / stream / line combinations.

### CODE REVIEW

**Comment by MindaugasSarpis** [comment]
Did we run out of recIDs?

**Comment by tiborsimko** [comment]
> Did we run out of recIDs?

Just ran into ones that were in the meantime taken by the CMS heavy ion release. 

Please use the new record ID interval starting from 28000.

**Review by tiborsimko — COMMENTED** [review]
@MindaugasSarpis Thanks! As spoken IRL, this PR touches already-released data streams, so I'll leave it out from the PR.

One minor change is related to descriptions:

- old way (_already released_): "proton-proton (pp) collision data collected by the LHCb experiment in the year 2012 of Run1 of the LHC."
- new way (_this PR_): "Data from proton-proton (pp) collisions collected by the LHCb experiment in the year 2012 of Run1 of the LHC."

Which one do you prefer?

**Comment by tiborsimko** [comment]
> Which one do you prefer?

What I did:

- Retained already-released records and just amended their abstract according to new records.
- Removed extra newline characters and spaces by basically doing:

```shell
sed -i -e 's/\s*\\n\s*/ /g' cernopendata/modules/fixtures/data/records/LHCb_201*json
sed -i -e 's/"release": " /"release": "/g' cernopendata/modules/fixtures/data/records/LHCb_201*json
sed -i -e 's/"description": "proton-proton (pp) collision data collected/"description": "Data from proton-proton (pp) collisions collected/g' cernopendata/modules/fixtures/data/records/LHCb_201*json

```

**Pull request merged**
