### PR TITLE
templates: CMS: small modifications

### PR DESCRIPTION
**Pull request by atrisovic**
* Closes: #1871
  * Closes: #1679

Signed-off-by: Ana Trisovic <ana.trisovic@gmail.com>

### CODE REVIEW

**Comment by atrisovic** [comment]
Fixed now

**Comment by ioannistsanaktsidis** [comment]
@atrisovic  is this one ready ?

**Comment by atrisovic** [comment]
yes

**Comment by ioannistsanaktsidis** [comment]
Please rebase and I will merge.

**Comment by atrisovic** [comment]
Done 👍

**Pull request merged**
