### PR TITLE
search: New facets implementation

### PR DESCRIPTION
**Pull request by annatrz**
* new faceting implementation with logical OR within one aggregation type, and AND for others
* add clear facet option for subaggregations
* when parent aggregation checked, check all subaggregations
* checking subaggregation automatically checks parent aggregation
* adjust mappings for Elasticsearch 5.x

### CODE REVIEW

**Comment by tiborsimko** [comment]
@annatrz Note the failed PEP-8 check...

**Comment by ioannistsanaktsidis** [comment]
Can we merge this one ? @tiborsimko @annatrz  just asking due to es@5 discussions ...

**Comment by annatrz** [comment]
Just need to change mappings (aggregations not working properly with ES5.x) and can go

**Comment by tiborsimko** [comment]
@annatrz Is there a particular Elasticsearch 5.x version that is necessary for the new facets to work? CC @hjhsalo who is setting up the containers...

**Comment by annatrz** [comment]
I'm working with Elasticsearch 5.0, but i guess all 5.x should work (from faceting point of view, don't know about other invenio modules requirements)

**Comment by annatrz** [comment]
Ok, mappings adjusted, hopefully ready to go :)

**Pull request merged**
