### PR TITLE
records: CMS 2012 HLT configuration files

### LINKED ISSUE #1961: records: generate CMS 2012 HLT configuration files
Stemmed from #1189

### PR DESCRIPTION
**Pull request by tiborsimko**
* Adds CMS HLT configuration files for 2012. (closes #1961)

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

### CODE REVIEW

**Comment by tiborsimko** [comment]
@ArtemisLav @katilp Please note the run period information... using the dashed variant until we solve https://github.com/cernopendata/opendata.cern.ch/issues/1189#issuecomment-347898882 ...

**Comment by katilp** [comment]
NB, we do host all data-taking config files for the entire year (for DP purposes and for eventual addition of remaining data to the portal), so those before 193833 would be RunA, and those after 203742 for RunD.

**Comment by tiborsimko** [comment]
@katilp Thanks, so this is my understanding:

```
2012RunA:

CMSSW_5_2_3_patch1_ONLINE /cdaq/physics/Run2012/5e33/v4.4/HLT/V5 (runs 190456 - 190465)
CMSSW_5_2_3_patch1_ONLINE /cdaq/physics/Run2012/5e33/v4.4/HLT/V7 (runs 190482 - 190539)
CMSSW_5_2_3_patch1_ONLINE /cdaq/physics/Run2012/5e33/v4.5/HLT/V3 (runs 190591 - 190595)
CMSSW_5_2_3_patch1_ONLINE /cdaq/physics/Run2012/5e33/v4.6/HLT/V5 (runs 190645 - 190659)
CMSSW_5_2_3_patch1_ONLINE /cdaq/physics/Run2012/5e33/v4.7/HLT/V1 (runs 190661 - 190679)
CMSSW_5_2_3_patch1_ONLINE /cdaq/physics/Run2012/5e33/v4.8/HLT/V1 (runs 190688 - 190738)
CMSSW_5_2_3_patch1_ONLINE /cdaq/physics/Run2012/5e33/v4.10/HLT/V (run 190782)
CMSSW_5_2_3_patch1_ONLINE /cdaq/physics/Run2012/5e33/v4.11/HLT/V (runs 190895 - 190906)
CMSSW_5_2_3_patch4_ONLINE /cdaq/physics/Run2012/5e33/v4.12/HLT/V (runs 190945 - 190949)
CMSSW_5_2_3_patch4_ONLINE /cdaq/physics/Run2012/5e33/v4.13/HLT/V (runs 191043 - 191090)
CMSSW_5_2_3_patch4_ONLINE /cdaq/physics/Run2012/5e33/v4.14/HLT/V (runs 191201 - 191411)
CMSSW_5_2_4_onlpatch1_ONLINE /cdaq/physics/Run2012/5e33/v4.16/HLT/V2 (runs 191691 - 191726)
CMSSW_5_2_4_onlpatch1_ONLINE /cdaq/physics/Run2012/5e33/v4.16/HLT/V3 (runs 191800 - 191859)
CMSSW_5_2_4_onlpatch1_ONLINE /cdaq/physics/Run2012/5e33/v4.16/HLT/V14 (runs 193093 - 193124)
CMSSW_5_2_4_onlpatch1_ONLINE /cdaq/physics/Run2012/5e33/v4.16/HLT/V15 (runs 193192 - 193207)
CMSSW_5_2_4_onlpatch1_ONLINE /cdaq/physics/Run2012/5e33/v4.16/HLT/V18 (runs 193334 - 193336)
CMSSW_5_2_4_onlpatch1_ONLINE /cdaq/physics/Run2012/5e33/v4.16/HLT/V21 (runs 193541 - 193621)

2012RunB:

CMSSW_5_2_4_onlpatch3_ONLINE /cdaq/physics/Run2012/7e33/v2.1/HLT/V11 (runs 193834 - 193836)
CMSSW_5_2_4_onlpatch3_ONLINE /cdaq/physics/Run2012/7e33/v2.1/HLT/V12 (runs 193998 - 194210)
CMSSW_5_2_4_onlpatch3_ONLINE /cdaq/physics/Run2012/7e33/v2.1/HLT/V13 (runs 194223 - 194225)
CMSSW_5_2_4_onlpatch3_ONLINE /cdaq/physics/Run2012/7e33/v2.2/HLT/V2 (runs 194270 - 194317)
CMSSW_5_2_4_onlpatch3_ONLINE /cdaq/physics/Run2012/7e33/v2.2/HLT/V3 (runs 194424 - 194712)
CMSSW_5_2_4_onlpatch3_ONLINE /cdaq/physics/Run2012/7e33/v2.3/HLT/V1 (runs 194735 - 194778)
CMSSW_5_2_4_onlpatch3_ONLINE /cdaq/physics/Run2012/7e33/v2.3/HLT/V2 (runs 194788 - 194825)
CMSSW_5_2_4_onlpatch3_ONLINE /cdaq/physics/Run2012/7e33/v2.3/HLT/V3 (runs 194896 - 195970)
CMSSW_5_2_4_onlpatch4_ONLINE /cdaq/physics/Run2012/7e33/v2.3/HLT/V3 (runs 196019 - 196027)
CMSSW_5_2_4_onlpatch3_ONLINE /cdaq/physics/Run2012/7e33/v2.4/HLT/V1 (runs 195868 - 195950)
CMSSW_5_2_4_onlpatch4_ONLINE /cdaq/physics/Run2012/7e33/v2.5/HLT/V1 (runs 196046 - 196531)

2012RunD:

CMSSW_5_2_4_onlpatch5_ONLINE /cdaq/physics/Run2012/7e33/v3.0/HLT/V2 (run 198022)
CMSSW_5_2_4_onlpatch5_ONLINE /cdaq/physics/Run2012/7e33/v3.0/HLT/V3 (runs 198023 - 198049)
CMSSW_5_2_4_onlpatch5_ONLINE /cdaq/physics/Run2012/7e33/v3.0/HLT/V4 (runs 198050 - 198063)
CMSSW_5_2_4_onlpatch5_ONLINE /cdaq/physics/Run2012/7e33/v3.0/HLT/V5 (runs 198116 - 198230)
CMSSW_5_2_4_onlpatch5_ONLINE /cdaq/physics/Run2012/7e33/v3.1/HLT/V1 (runs 198249 - 199021)
CMSSW_5_2_4_onlpatch5_ONLINE /cdaq/physics/Run2012/7e33/v3.1/HLT/V2 (runs 199318 - 199608)
CMSSW_5_2_6_onlpatch2_ONLINE /cdaq/physics/Run2012/7e33/v4.0/HLT/V1 (runs 199698 - 199877)
CMSSW_5_2_6_onlpatch2_ONLINE /cdaq/physics/Run2012/7e33/v4.0/HLT/V4 (runs 199960 - 200381)
CMSSW_5_2_6_onlpatch3_ONLINE /cdaq/physics/Run2012/7e33/v4.1/HLT/V1 (runs 200466 - 202504)
CMSSW_5_2_6_onlpatch3_ONLINE /cdaq/physics/Run2012PI/PilotRun/PIHLT/V2 (run 202792)
CMSSW_5_2_6_onlpatch3_ONLINE /cdaq/physics/Run2012PI/PilotRun/PIHLT/V4 (runs 202793 - 202794)
CMSSW_5_2_6_onlpatch3_ONLINE /cdaq/physics/Run2012/7e33/v4.2/HLT/V1 (runs 202970 - 203002)
CMSSW_5_2_7_cand3_ONLINE-cms /cdaq/physics/Run2012/7e33/v4.2/HLT/V1 (run 203709)

2012RunD:

CMSSW_5_2_7_ONLINE /cdaq/physics/Run2012/8e33/v1.0/HLT/V2 (runs 203777 - 203994)
CMSSW_5_2_7_ONLINE /cdaq/physics/Run2012/8e33/v1.1/HLT/V1 (runs 204100 - 205238)
CMSSW_5_2_7_onlpatch1_ONLINE /cdaq/physics/Run2012/8e33/v1.2/HLT/V1 (runs 205303 - 205834)
CMSSW_5_2_7_onlpatch2_ONLINE /cdaq/physics/Run2012/8e33/v1.2/HLT/V1 (runs 205908 - 206605)
CMSSW_5_2_7_onlpatch2_ONLINE /cdaq/physics/Run2012/8e33/v2.0/HLT/V2 (runs 206744 - 206745)
CMSSW_5_2_7_onlpatch2_ONLINE /cdaq/physics/Run2012/8e33/v2.0/HLT/V3 (runs 206859 - 207100)
CMSSW_5_2_7_onlpatch3_ONLINE /cdaq/physics/Run2012/8e33/v2.1/HLT/V5 (runs 207214 - 207518)
CMSSW_5_2_7_onlpatch3_ONLINE /cdaq/physics/Run2012/8e33/v2.1/HLT/V6 (runs 207779 - 207886)
CMSSW_5_2_7_onlpatch3_ONLINE /cdaq/physics/Run2012/8e33/v2.1/HLT/V7 (runs 207887 - 208686)
```

I'll amend the information accordingly.

**Comment by tiborsimko** [comment]
OK, updated.

**Comment by tiborsimko** [comment]
> Run2010B, Run2012B, Run2012C and so on, whereas you have 2012RunC

Whoops! Fixed. Must have got distracted by those 2012RunBlumi files 😄

> Could you perhaps check if this syntax is indeed consistent everywhere else and amend accordingly?

Checked and there is one more problem with record 1802, also in COD2... Gonna make a PR for it.

**Pull request merged**
