### PR TITLE
CMS: trigger path records

### PR DESCRIPTION
**Pull request by tiborsimko**
* Adds CMS Trigger path records for Run2011A.  (addresses #832)

Signed-off-by: Tibor Simko <tibor.simko@cern.ch>

### CODE REVIEW

**Comment by tiborsimko** [comment]
This PR adds 956 separate records representing CMS Trigger Paths as discussed in #832.  The template is simple:

```xml
  <record>
    <controlfield tag="001">2000</controlfield>
    <datafield tag="110" ind1=" " ind2=" ">
        <subfield code="a">CMS collaboration</subfield>
    </datafield>
    <datafield tag="245" ind1=" " ind2=" ">
        <subfield code="a">Trigger Path AForHIOutput</subfield>
    </datafield>
    <datafield tag="260" ind1=" " ind2=" ">
        <subfield code="b">CERN Open Data Portal</subfield>
        <subfield code="c">2016</subfield>
    </datafield>
    <datafield tag="264" ind1=" " ind2="0">
        <subfield code="c">2011</subfield>
    </datafield>
    <datafield tag="520" ind1=" " ind2=" ">
        <subfield code="a"><![CDATA[<p>first seen online on run 181530 (/cdaq/special/HeavyIon/HLT_HIon2011_L1TimingTest/V2)</p><p>last  seen online on run 183126 (/cdaq/physics/Run2011HI/v1.7/HIHLT/V1)</p><p>unversioned: (runs 181530 - 183126)</p>]]></subfield>
    </datafield>
    <datafield tag="942" ind1=" " ind2=" ">
        <subfield code="e">7TeV</subfield>
    </datafield>
    <datafield tag="980" ind1=" " ind2=" ">
        <subfield code="a">CMS-Trigger-Information</subfield>
    </datafield>
  </record>
``` 

@AnxhelaDani @pherterich @suenjedt Any default fields to add? Where do we store trigger names so that we could link them easily from dataset records? Do we structure information inside abstract body (as we've been doing so far) or do we start multiple independent abstract information units?

@katilp Any comment regarding record titles or descriptions?  Can show you tomorrow how things look.

**Comment by tiborsimko** [comment]
2016-02-01-142707_2560x1440_scrot

**Comment by AnxhelaDani** [comment]
@tiborsimko the additional fields are:
'''693 $a CERN-LHC $e CMS
  980 $b Research'''

**Comment by tiborsimko** [comment]
Thanks, added.

**Pull request merged**
