### PR TITLE
Stand-alone CMS event display

### PR DESCRIPTION
**Pull request by tpmccauley**
This PR fixes the remaining issues found at:
https://github.com/cernopendata/opendata.cern.ch/issues/1539

### CODE REVIEW

**Comment by ioannistsanaktsidis** [comment]
@tpmccauley please rebase against latest master so as to merge.

**Comment by tpmccauley** [comment]
Done

**Comment by ioannistsanaktsidis** [comment]
@tpmccauley still shown outdated :/

**Comment by tiborsimko** [comment]
@ioannistsanaktsidis Since we shall be in a merging frenzy these days 😄, it may not be easy for @tpmccauley to find an appropriate time to rebase... It seems better if you cherry-pick @tpmccauley's commit, and put it onto some of your own branch event display branches, and we merge that way?

**Comment by ioannistsanaktsidis** [comment]
No problem by me :) will create a separate PR .

**Comment by ioannistsanaktsidis** [comment]
Closing as superseded by #1678 .

**Pull request closed without merging**
