### PR TITLE
CMS: adds software record for event display files

### LINKED ISSUE #2025: Software record for event display file code
As pointed out in #1993 we should have a record for the event display file production code a la http://opendata.cern.ch/record/550

The new urls are

https://github.com/cms-outreach/ispy-analyzers/tree/Run2012
https://github.com/cms-outreach/ispy-services

Is a pointer to a branch fine as before or is a tag preferred?

### PR DESCRIPTION
**Pull request by ArtemisLav**
* Adds one new software record for CMS 2012 event display files.
(closes #2025)

Signed-off-by: Artemis Lavasa <artemis.lavasa@cern.ch>

### CODE REVIEW

**Comment by ArtemisLav** [comment]
This probably shouldn't have the exact same title as record 550. Shall I add a "2012" somewhere in there or what would be the best way to differentiate?

**Comment by tpmccauley** [comment]
Perhaps
"Software to extract the data for the browser-based event display for the CMS Experiment" -> "Software to create the data for the browser-based event display for the CMS Experiment from the Run2012 primary datasets"

**Comment by ArtemisLav** [comment]
That is the description; the title is "Software to extract the event display format from the CMS primary dataset".  I can amend the description as well though, thanks.

**Comment by ArtemisLav** [comment]
@tiborsimko Done. For the title, I just added "from the Run2012" at the end.

**Pull request merged**
