### PR TITLE
docs: add short description

### PR DESCRIPTION
**Pull request by atrisovic**
Signed-off-by: Ana Trisovic <ana.trisovic@gmail.com>

### CODE REVIEW

**Comment by pamfilos** [comment]
```short_description``` field is an object with ```type``` and ```content``` as properties inside

as in https://github.com/cernopendata/opendata.cern.ch/blob/master/cernopendata/jsonschemas/records/docs-v1.0.0.json#L43

have you tried it locally?

**Comment by atrisovic** [comment]
This is now updated!

**Comment by ArtemisLav** [comment]
I think we need this for the new CMS article as well.

**Comment by atrisovic** [comment]
I can still see markdown even with `short_description` 😟

**Comment by justintarver2016** [comment]
W t f

**Comment by tiborsimko** [comment]
> I can still see markdown even with short_description 😟

I see the new short descriptions fine.  Please rebase and this is good to go...

**Pull request merged**
